### ISSUE TITLE
user-can-see-their-car 

### ISSUE THREAD

**Issue by Michael-M-Aguilar** [Michael-M-Aguilar/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [ ] Create a div with a container class.
- [ ] Create a div with the row class.
- [ ] Make the container have a background-color of hexcode: #288D26
- [ ] Have the head have the title "Driving Game"
- [ ] Insert the "favicon.ico 256x256" be the "logo" for the head.
- [ ] Insert the image "f1.svg" to be a child of the div with the "row" class. 
- [ ] Assure that the f1 car "starts" on the top left corner of the page.
